//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RobotResult", Namespace="http://clorofeel.quidmind.com/DataModel/RobotResult")]
    [System.SerializableAttribute()]
    public partial class RobotResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Compass {
            get {
                return this.CompassField;
            }
            set {
                if ((this.CompassField.Equals(value) != true)) {
                    this.CompassField = value;
                    this.RaisePropertyChanged("Compass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatusOk {
            get {
                return this.StatusOkField;
            }
            set {
                if ((this.StatusOkField.Equals(value) != true)) {
                    this.StatusOkField = value;
                    this.RaisePropertyChanged("StatusOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://clorofeel.quidmind.com/ServiceModel/RobotVideo", ConfigurationName="ClorofeelCloudServices.RobotVideo")]
    public interface RobotVideo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/SendLastPicture", ReplyAction="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/SendLastPictureR" +
            "esponse")]
        void SendLastPicture(string secureToken, int positionBoussolle, string pictureBase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/GetLastPicture", ReplyAction="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/GetLastPictureRe" +
            "sponse")]
        QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices.RobotResult GetLastPicture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/TestMethod", ReplyAction="http://clorofeel.quidmind.com/ServiceModel/RobotVideo/RobotVideo/TestMethodRespon" +
            "se")]
        string TestMethod();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RobotVideoChannel : QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices.RobotVideo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotVideoClient : System.ServiceModel.ClientBase<QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices.RobotVideo>, QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices.RobotVideo {
        
        public RobotVideoClient() {
        }
        
        public RobotVideoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RobotVideoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotVideoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotVideoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendLastPicture(string secureToken, int positionBoussolle, string pictureBase64) {
            base.Channel.SendLastPicture(secureToken, positionBoussolle, pictureBase64);
        }
        
        public QuidMind.CloRoFeel.CamGrabber.ClorofeelCloudServices.RobotResult GetLastPicture() {
            return base.Channel.GetLastPicture();
        }
        
        public string TestMethod() {
            return base.Channel.TestMethod();
        }
    }
}
